### ISSUE TITLE
Clone the source code. And then the compilation error.

### ISSUE THREAD

**Issue by 846524417** [hrydgard/ppsspp#12136]
Clone the source code. And then the compilation error.
And then I did nothing. I compiled it.Is this a submodule error?
Anybody know? Thank you very much!

**Comment by 846524417** [comment]
![image](https://user-images.githubusercontent.com/51825152/60158788-5f805000-9824-11e9-9e6d-211235720f27.png)

**Comment by hrydgard** [comment]
hard to say from that output.

Did you do 

```git clone --recursive``` ?

If not, do 

```git submodule update --init --recursive``` to fix it.

If that doesn't help, I'm not sure. Is that Android Studio 3.4?

**Comment by 846524417** [comment]
Yes, I have executed the update submodule.I just updated it again.But nothing is the same.
Is AndroidStudio3.4.1

**Comment by hrydgard** [comment]
Hm, it's looking for Python, sounds like the same issue we had on Travis.

Should really find a better way, but it might help to install Python 3.6 from https://www.python.org/ in the meantime. Could you try that?

**Comment by 846524417** [comment]
Well, I'll try it right away

**Comment by 846524417** [comment]
It doesn't seem to be very useful.I managed to install Python3.6 and it still works in Python3.6.
My NDK is 17. I don't know if the last mistake of NDK20r has been solved.
![image](https://user-images.githubusercontent.com/51825152/60163409-21882980-982e-11e9-84f0-be9aa835673b.png)
![image](https://user-images.githubusercontent.com/51825152/60163430-32389f80-982e-11e9-8465-59b839a03fd2.png)

**Comment by hrydgard** [comment]
Maybe try to restart the PC after installing python? Paths and stuff you know.

Right, if you want to build for ARM 32-bit you will need NDK 19.  But if you choose ARM64 and plug in an ARM64 device and press Run, it should avoid all that and just build for your device, which would work with NDK 20.

**Comment by 846524417** [comment]
But I'm using 17b, so I don't think that's going to be a problem.

**Comment by 846524417** [comment]
I tested both computers and found the same problem. There was no such problem before.

**Comment by hrydgard** [comment]
Right, that SDK should still work I think. Then I don't quite understand what's going on. Try deleting the External directory inside the ext/glslang directory, that might remove the python dependency.

**Comment by 846524417** [comment]
If it's python, I didn't install python before, but it worked fine.Is there anything new recently?

**Comment by hrydgard** [comment]
I upgraded glslang and SPIRV-cross, and a strange new dependency seems to have snuck in.

**Comment by 846524417** [comment]
I think there's something wrong with the glouch and spirv-cross modules.

**Comment by hrydgard** [comment]
I'll look into it soon, but can you try what I suggested above about deleting the ext/glslang/External directory locally?

**Comment by 846524417** [comment]
After I deleted the ext/ glmouse /External directory as you said before, it didn't help either.
![image](https://user-images.githubusercontent.com/51825152/60167448-b4789200-9835-11e9-8479-69f8f9746c7e.png)
![image](https://user-images.githubusercontent.com/51825152/60167771-526c5c80-9836-11e9-8596-2960e0b2bd44.png)

**Comment by 846524417** [comment]
Has the submodule problem been solved? @ @hrydgard

**Comment by 846524417** [comment]
Can you upload a successful project? @hrydgard

**Comment by hrydgard** [comment]
I really don't understand this one. I just cloned and built on a fresh machine and had no problems.

**Comment by unknownbrackets** [comment]
Isn't this issue just that Python 3 must be installed now?

-[Unknown]

**Comment by 846524417** [comment]
现在好了，我并没有做什么！只是在不断的更新项目。Python 3 也并没有安装

**Comment by 846524417** [comment]
Now, I'm not doing anything! It's just constantly updating projects. Python 3 is not installed either

**Comment by 846524417** [comment]
No problem now.

**Comment by unknownbrackets** [comment]
We should add python to the build instructions, I suppose.

-[Unknown]
