### ISSUE TITLE
Using system-wide ffmpeg

### ISSUE THREAD

**Issue by akien-mga** [hrydgard/ppsspp#5772]
Hi,

Now that ffmpeg 2.2 has been released with Atrac3+ support, do you know if it would be possible to build PPSSPP against the system's ffmpeg shared libraries? I'm packaging PPSSPP for Mageia and I would really like to avoid having to bundle a fork of ffmpeg.

For now I'm using a patch from OpenMandriva that lets me build PPSSPP with Mageia's ffmpeg 2.2: https://abf.rosalinux.ru/openmandriva/ppsspp/blob/master/ppsspp-0.9.6-ffmpeg.patch (I rediffed it a bit for PPSSPP 0.9.8 since there were some code changes since 0.9.6).

Videos work fine, but Atrac3+ sound doesn't, even with ffmpeg 2.2.

**Comment by hrydgard** [comment]
With #7344 merged, this should now work. Will close on confirmation.

**Comment by akien-mga** [comment]
I've just built the master branch; the Qt version builds fine against the system ffmpeg using ```CONFIG+="system_ffmpeg"```, but there is still the same issue with atrac3p playback, at least with Crysis Core:
```
58:53:993 SQEXTEC Movi E[ME]: HW/SimpleAudioDec.cpp:201 Error decoding Audio frame (744 bytes): -22 (ffffffea)
58:53:993 SQEXTEC Movi E[ME]: HW/MediaEngine.cpp:803 Audio (AT3+) decode failed during video playback
```

**Comment by unknownbrackets** [comment]
Just merged a new change which may fix that.

-[Unknown]

**Comment by akien-mga** [comment]
I just backported https://github.com/unknownbrackets/ppsspp/commit/daa90024ed57a722033a72268c11afc8e918eda2 and it works great with ffmpeg 2.4.5.

**Comment by akien-mga** [comment]
Here's a recording of the atrac3p playback with PPSSPP master and @unknownbrackets's latest patch on Crysis Core: http://remi.verschelde.fr/files/misc/ppsspp-recording.ogg

**Comment by unknownbrackets** [comment]
Well, if there are any issues maybe it's resampling related or something.  It's probably not ffmpeg related.

I'll close this now since it works on the latest ffmpeg without patches now.  Probably will update to a more recent ffmpeg but that's more related to #6283.

-[Unknown]

**Comment by akien-mga** [comment]
I agree, I just built the PPSSPPSDL against the static ffmpeg libraries to compare, and there seems to be the same resampling issues, so it's indeed not related to this issue. Thanks for your work :-)

**Comment by unknownbrackets** [comment]
Most likely it was caused by #7315.  I wonder if there's a better way to mix and get the optimal native sample rate on Linux.

-[Unknown]
