### ISSUE TITLE
Build failure on 32-bit systems

### ISSUE THREAD

**Issue by orbea** [hrydgard/ppsspp#9094]
OS: `Slackware-14.2`

When trying to build ppsspp on a 32-bit Slackware system it will fail. Building on a x86_64 system will work.
```
[ 73%] Building CXX object CMakeFiles/Core.dir/Core/Host.cpp.o
/tmp/SBo/ppsspp/Core/HW/MediaEngine.cpp: In member function 'bool MediaEngine::openContext(bool)':
/tmp/SBo/ppsspp/Core/HW/MediaEngine.cpp:299:64: error: 'av_dict_set_int' was not declared in this scope
     av_dict_set_int(&open_opt, "probesize", m_mpegheaderSize, 0);
                                                                ^
CMakeFiles/Core.dir/build.make:3710: recipe for target 'CMakeFiles/Core.dir/Core/HW/MediaEngine.cpp.o' failed
make[2]: *** [CMakeFiles/Core.dir/Core/HW/MediaEngine.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:202: recipe for target 'CMakeFiles/Core.dir/all' failed
make[1]: *** [CMakeFiles/Core.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```
Build log - http://pastebin.com/UDZnpND7

The first bad commit.
```
dcc2541b7192b63bf46541065d8ba071eab00bbe is the first bad commit
commit dcc2541b7192b63bf46541065d8ba071eab00bbe
Author: Unknown W. Brackets <checkins@unknownbrackets.org>
Date:   Sun Jun 5 16:35:14 2016 -0700

    Mpeg: Ask FFmpeg not to look beyond the header.

:040000 040000 2b3a458d020be177786efbf8dd0544cce6ae532e e8f39dc373566c8a9df6ccea5afe35dc0b941939 M	Core
```
dcc2541b7192b63bf46541065d8ba071eab00bbe

**Comment by orbea** [comment]
@unknownbrackets Can you take a look at this?

**Comment by hrydgard** [comment]
I guess the build rules in the CMakeLists.txt results in building using the system FFMPEG on your machine, and it's not the right version. What version of ffmpeg is included with your system?

**Comment by orbea** [comment]
This should be building with the ffmpeg submodule, the clean slackware chroot I tested this on does not have ffmpeg installed.

`Submodule path 'ffmpeg': checked out '81379c5caa96842af51f4cdd512f32fa39089874'`

**Comment by hrydgard** [comment]
Oh, maybe the 32-bit linux ffmpeg has fallen behind and needs a rebuild...

**Comment by orbea** [comment]
Seems the 32-bit linux ffmpeg was last updated 3 years ago, is it documented how fffmpeg is built for ppsspp?

**Comment by mrcmunir** [comment]
You will use script in the shell from ppsspp-fmpeg submodule https://github.com/hrydgard/ppsspp-ffmpeg

./linux_x86.sh in ffmpeg/

**Comment by orbea** [comment]
Thanks, I overlooked that. I hope I did it right? It works at least on my end.
