### ISSUE TITLE
Error compiling with GCC-5.4

### ISSUE THREAD

**Issue by latot** [hrydgard/ppsspp#9178]
Hi, as the title says, i can't compile ppsspp with gcc-5.4:

```
In file included from /home/pipe/Documentos/git/ppsspp/ext/glslang/glslang/MachineIndependent/../Include/InfoSink.h:39:0,
                 from /home/pipe/Documentos/git/ppsspp/ext/glslang/glslang/MachineIndependent/intermOut.cpp:38:
/home/pipe/Documentos/git/ppsspp/ext/glslang/glslang/MachineIndependent/intermOut.cpp: En la función ‘bool {anónimo}::is_positive_infinity(double)’:
/home/pipe/Documentos/git/ppsspp/ext/glslang/glslang/MachineIndependent/intermOut.cpp:52:15: error: expected unqualified-id before ‘(’ token
   return std::isinf(x) && (x >= 0);
```

I use Gentoo 64.

Thx. Cya.

**Comment by hrydgard** [comment]
another glslang bug? you've properly updated your submodules, right? if not it should be enough to rm -rf ext/glslang and then git submodule init --update --recursive.

Since we are now using upstream glslang, this should really be reported at https://github.com/KhronosGroup/glslang if it's still an issue.

**Comment by latot** [comment]
okis, i have the submodules updated, seems you have a little of experience with gslang bugs..

Linking!

https://github.com/KhronosGroup/glslang/issues/642

Thx. Cya.

**Comment by Orphis** [comment]
@hrydgard Actually, git submodule sync --recursive and then git submodule init --update --recursive are the proper commands!

**Comment by latot** [comment]
in my case i use ```git submodule update --recursive```

**Comment by mrcmunir** [comment]
@latot Add #include <cmath> in that file I compile fine with GCC5.4 compiler

**Comment by latot** [comment]
submodules are ok, reseted, rysync, etc...., and nice, that fix the issue!, updating upstream

**Comment by latot** [comment]
Hi, this issue is already fixed in upstream, @hrydgard is possible update gslang branch of ppsspp with upstream?, or just fix this?

in the last case is only change ```math.c``` to ```cmath```

Thx. Cya

**Comment by hrydgard** [comment]
Right, I'll update it. Thanks!

**Comment by hrydgard** [comment]
Done! Please reopen if there are still issues.

**Comment by latot** [comment]
Hi!, now works, Thx!
