### PR TITLE
Socket inconsistency platform fixes - broken out from #13132

### PR DESCRIPTION
**Pull request by hrydgard**
More stuff broken out from #13132.

### CODE REVIEW

**Comment by Sanaki** [comment]
This appears to have broken the libretro build in a way that may affect other builds as well:
```
../Core/HLE/sceNet.o: In function `__NetInit()':
sceNet.cpp:(.text._Z9__NetInitv+0xd3): undefined reference to `g_PortManager'
sceNet.cpp:(.text._Z9__NetInitv+0xdd): undefined reference to `PortManager::Init(unsigned int)'
../Core/HLE/sceNet.o: In function `__NetShutdown()':
sceNet.cpp:(.text._Z13__NetShutdownv+0xa3): undefined reference to `g_PortManager'
sceNet.cpp:(.text._Z13__NetShutdownv+0xab): undefined reference to `PortManager::Clear()'
sceNet.cpp:(.text._Z13__NetShutdownv+0xb3): undefined reference to `PortManager::Restore()'
sceNet.cpp:(.text._Z13__NetShutdownv+0xbc): undefined reference to `PortManager::Deinit()'
../Core/HLE/sceNetAdhoc.o: In function `void WrapI_IUUII<&(sceNetAdhocPtpAccept(int, unsigned int, unsigned int, int, int))>()':
sceNetAdhoc.cpp:(.text._Z11WrapI_IUUIIIXadL_ZL20sceNetAdhocPtpAcceptijjiiEEEvv+0x512): undefined reference to `g_PortManager'
sceNetAdhoc.cpp:(.text._Z11WrapI_IUUIIIXadL_ZL20sceNetAdhocPtpAcceptijjiiEEEvv+0x523): undefined reference to `PortManager::Add(unsigned short, char const*)'
../Core/HLE/sceNetAdhoc.o: In function `sceNetAdhocPdpCreate(char const*, int, int, unsigned int)':
sceNetAdhoc.cpp:(.text._ZL20sceNetAdhocPdpCreatePKciij+0x7c0): undefined reference to `g_PortManager'
sceNetAdhoc.cpp:(.text._ZL20sceNetAdhocPdpCreatePKciij+0x7cb): undefined reference to `PortManager::Add(unsigned short, char const*)'
../Core/HLE/sceNetAdhoc.o: In function `sceNetAdhocPtpListen(char const*, int, int, int, int, int, int)':
sceNetAdhoc.cpp:(.text._ZL20sceNetAdhocPtpListenPKciiiiii+0x8d8): undefined reference to `g_PortManager'
sceNetAdhoc.cpp:(.text._ZL20sceNetAdhocPtpListenPKciiiiii+0x8e2): undefined reference to `PortManager::Add(unsigned short, char const*)'
../Core/HLE/sceNetAdhoc.o: In function `sceNetAdhocPtpOpen(char const*, int, char const*, int, int, int, int, int)':
sceNetAdhoc.cpp:(.text._ZL18sceNetAdhocPtpOpenPKciS0_iiiii+0x2f4): undefined reference to `g_PortManager'
sceNetAdhoc.cpp:(.text._ZL18sceNetAdhocPtpOpenPKciS0_iiiii+0x32b): undefined reference to `PortManager::Add(unsigned short, char const*)'
../Core/HLE/proAdhocServer.o: In function `proAdhocServerThread(int)':
proAdhocServer.cpp:(.text._Z20proAdhocServerThreadi+0x7e): undefined reference to `g_PortManager'
proAdhocServer.cpp:(.text._Z20proAdhocServerThreadi+0x90): undefined reference to `PortManager::Add(unsigned short, char const*)'
proAdhocServer.cpp:(.text._Z20proAdhocServerThreadi+0xac): undefined reference to `PortManager::Remove(unsigned short, char const*)'
collect2: error: ld returned 1 exit status
Makefile:574: recipe for target 'ppsspp_libretro.so' failed
```

**Comment by hrydgard** [comment]
Hm, the libretro build passed our CI. From the errors it looks like PortManager.cpp is not being compiled and/or linked, which hm, indeed seems to be the case that it's missing from the retro makefile. I'll commit a quick fix.

**Comment by hrydgard** [comment]
@Sanaki  Committed, please test.

**Comment by Sanaki** [comment]
No dice.
```
../Core/Util/PortManager.o: In function `PortManager::Clear() [clone .part.0]':
PortManager.cpp:(.text._ZN11PortManager5ClearEv.part.0+0x139): undefined reference to `UPNP_GetGenericPortMappingEntry'
PortManager.cpp:(.text._ZN11PortManager5ClearEv.part.0+0x1cf): undefined reference to `UPNP_DeletePortMapping'
../Core/Util/PortManager.o: In function `PortManager::Restore()':
PortManager.cpp:(.text._ZN11PortManager7RestoreEv+0x68b): undefined reference to `UPNP_DeletePortMapping'
PortManager.cpp:(.text._ZN11PortManager7RestoreEv+0x726): undefined reference to `UPNP_AddPortMapping'
../Core/Util/PortManager.o: In function `PortManager::RefreshPortList()':
PortManager.cpp:(.text._ZN11PortManager15RefreshPortListEv+0x3ab): undefined reference to `UPNP_GetGenericPortMappingEntry'
../Core/Util/PortManager.o: In function `PortManager::Init(unsigned int)':
PortManager.cpp:(.text._ZN11PortManager4InitEj+0xf4): undefined reference to `upnpDiscover'
PortManager.cpp:(.text._ZN11PortManager4InitEj+0x17e): undefined reference to `miniwget'
PortManager.cpp:(.text._ZN11PortManager4InitEj+0x196): undefined reference to `parserootdesc'
PortManager.cpp:(.text._ZN11PortManager4InitEj+0x1b2): undefined reference to `GetUPNPUrls'
PortManager.cpp:(.text._ZN11PortManager4InitEj+0x216): undefined reference to `UPNP_GetValidIGD'
PortManager.cpp:(.text._ZN11PortManager4InitEj+0x379): undefined reference to `UPNP_GetConnectionTypeInfo'
PortManager.cpp:(.text._ZN11PortManager4InitEj+0x60c): undefined reference to `freeUPNPDevlist'
../Core/Util/PortManager.o: In function `PortManager::Deinit()':
PortManager.cpp:(.text._ZN11PortManager6DeinitEv+0x30): undefined reference to `FreeUPNPUrls'
../Core/Util/PortManager.o: In function `PortManager::Add(unsigned short, char const*)':
PortManager.cpp:(.text._ZN11PortManager3AddEtPKc+0x447): undefined reference to `UPNP_DeletePortMapping'
PortManager.cpp:(.text._ZN11PortManager3AddEtPKc+0x47e): undefined reference to `UPNP_AddPortMapping'
PortManager.cpp:(.text._ZN11PortManager3AddEtPKc+0xd4f): undefined reference to `UPNP_AddPortMapping'
../Core/Util/PortManager.o: In function `PortManager::Remove(unsigned short, char const*)':
PortManager.cpp:(.text._ZN11PortManager6RemoveEtPKc+0xef): undefined reference to `UPNP_DeletePortMapping'
collect2: error: ld returned 1 exit status
Makefile:574: recipe for target 'ppsspp_libretro.so' failed
```

**Comment by hrydgard** [comment]
Well, that's one step further. Forgot that we have to set up the whole miniupnp compile for libretro as well. That said, I have no idea how we are passing CI right now.

I'll try to fix it, stay tuned.

**Comment by hrydgard** [comment]
Ok, try now.

**Comment by ANR2ME** [comment]
Btw i think there is typo in the referenced tag on top of this page :D https://github.com/hrydgard/ppsspp/issues/13123 instead of https://github.com/hrydgard/ppsspp/pull/13132

**Comment by hrydgard** [comment]
Argh, too many similar digits :P

**Comment by Sanaki** [comment]
Sorry for the delay. That fixed it.
